const frases3 = [
  "Seja forte diante dos desafios 💪 Continue em frente com coragem 🚀 Acredite em você e no seu potencial 🌟 Nunca desista dos seus sonhos 🔥 A persistência abre portas que parecem fechadas 🏆",
      "Coragem é seguir mesmo com medo 🛡️ Sorria sempre mesmo nas dificuldades 😊 Tenha fé no seu caminho 🙏 A vitória vem para quem insiste 🏅 Cada erro traz aprendizado valioso 📚 O sucesso é construído com disciplina ✨",
      "A força interior move montanhas 🌈 Dedicação transforma objetivos em realidade 🌞 Determinação supera qualquer obstáculo 🎯 Resiliência é o segredo da conquista ⚡ Continue em frente com coragem 💪 Sorria sempre mesmo nas dificuldades 🚀",
      "Nunca desista dos seus sonhos 🌟 Seja forte diante dos desafios 🔥 Acredite em você e no seu potencial 🏆 A persistência abre portas que parecem fechadas 🛡️ O sucesso é construído com disciplina 😊 Tenha fé no seu caminho 🙏",
      "Cada erro traz aprendizado valioso 🏅 Dedicação transforma objetivos em realidade 📚 Coragem é seguir mesmo com medo ✨ A força interior move montanhas 🌈 Resiliência é o segredo da conquista 🌞 Determinação supera qualquer obstáculo 🎯",
      "A vida é uma jornada cheia de oportunidades 🌄 Encare cada desafio com coragem 💪 Tenha fé no seu potencial 🌟 Continue acreditando nos seus sonhos 🔥 O esforço diário constrói grandes conquistas 🏆",
      "Grandes vitórias começam com pequenos passos 👣 Cada ação conta 💥 Sorria mesmo nos momentos difíceis 😊 Persistência é o segredo do sucesso 🎯 Continue firme mesmo quando tudo parecer impossível ⚡",
      "Acredite que você pode 🌈 E o universo ajudará a realizar 💪 A cada dificuldade surge uma oportunidade 🚀 Tenha coragem de tentar novamente 🔥 Nunca perca a fé 🙏 E siga sempre com determinação 🌟",
      "A disciplina transforma sonhos em realidade 📚 Quem persiste mesmo diante das adversidades 💪 Encontra a força para superar 🌞 A vitória sorri para quem não desiste 🏅 Cada esforço vale a pena 💥",
      "O caminho pode ser difícil 🏔️ Mas cada desafio fortalece 🌟 Tenha paciência e confiança 💖 Cada passo dado com coragem 💪 Leva a grandes conquistas 🚀 O segredo é nunca desistir 🌈",
      // ... continue adicionando até completar 100 frases grandes];
